# Generated by Django 5.1.7 on 2025-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('video interview', 'Video Interview'), ('phone screen', 'Phone Screen'), ('online assessment', 'Online Assessment'), ('assessment centre', 'Assessment Centre'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='Applied', max_length=50)),
                ('applied_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
