# Generated by Django 5.1.7 on 2025-04-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
