# Generated by Django 5.1.7 on 2025-06-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('video interview', 'Video Interview'), ('phone screen', 'Phone Screen'), ('online assessment', 'Online Assessment'), ('assessment centre', 'Assessment Centre'), ('first interview', 'First Interview'), ('second interview', 'Second Interview'), ('third interview', 'Third Interview'), ('fourth interview', 'Fourth Interview'), ('fifth interview', 'Fifth Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('other', 'Other')], default='Applied', max_length=50),
        ),
    ]
