# Generated by Django 5.1.7 on 2025-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
    ]
